export const SELECTED_SUBREDDIT = "SELECTED_SUBREDDIT";

export const REQUEST_POSTS ="REQUEST_POSTS";

export const RECEIVE_POSTS = "RECEIVE_POSTS";

export const REFRESH_POSTS = "REFRESH_POSTS";